/*
 * A399244: number of set partitions of [n] into blocks whose element sums
 * are distinct primes.
 *
 * Let F(M,U) count completions of the remaining element mask M when U is
 * the set of prime sums already used.  Put the largest element of M in a
 * distinguished block B.  This fixes the order in which blocks are removed
 * and avoids counting a partition more than once:
 *
 *   F(0,U) = 1,
 *   F(M,U) = sum F(M \\ B, U union {sum(B)}),
 *
 * where B contains max(M), sum(B) is prime, and that prime is not in U.
 * The complete pair (M,U) is the memo key, so hash collisions cannot change
 * the result.  Candidate blocks are generated by meet-in-the-middle subset
 * sum for large states and ordinary submask enumeration for small states.
 * Root blocks are distributed through a dynamic pthread work queue.  All
 * For n <= 22, workers share a concurrent full-key memo table; busy entries
 * make duplicate states wait, and decreasing element counts make those waits
 * cycle-free.  For n >= 23, a fixed-size 4-way cache may evict complete
 * entries.  Eviction only causes recomputation: every returned count is still
 * calculated from a complete key, so it cannot change the exact result.
 * Prime-use sets are 128 bits wide (79 primes are needed through n=28).
 *
 * A necessary condition for a state to succeed is that sum(M) be a subset
 * sum of the unused primes.  A small bitset subset-sum calculation checks
 * this condition on demand.  Counts, additions, allocations, and table
 * loads are checked.  Known terms are used only by --self-test after a
 * value has been computed.
 *
 * Build:
 *   clang -O3 -march=native -std=c11 -Wall -Wextra -Wpedantic \
 *       399244_01.c -o 399244_01 -pthread
 *
 * Examples:
 *   ./399244_01 --upto 13 --threads 8 --self-test --stats
 *   ./399244_01 --target 19 --threads 8 --self-test --stats
 *
 * Each computed result is also written to b399244_01.txt in the current
 * directory.  The file is flushed and synchronized after every term, so a
 * completed prefix remains available if a long --upto run is interrupted.
 */

#include <errno.h>
#include <inttypes.h>
#include <pthread.h>
#include <sched.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#define MAX_N 28U
#define DEFAULT_N 13U
#define KNOWN_N 22U
#ifndef MITM_MIN_REST_SIZE
#define MITM_MIN_REST_SIZE 8U
#endif
#define PARALLEL_MIN_N 12U
#define TASK_CHUNK 16U
#define PROGRESS_MIN_N 23U
#define PROGRESS_INTERVAL_SECONDS 60.0
#define PROGRESS_POLL_NANOSECONDS 100000000L
#define MEMO_EMPTY 0U
#define MEMO_RESERVED 1U
#define MEMO_BUSY 2U
#define MEMO_COMPLETE 3U
#ifndef BOUNDED_MEMO_MIN_N
#define BOUNDED_MEMO_MIN_N 23U
#endif
#ifndef BOUNDED_MEMO_BITS
#define BOUNDED_MEMO_BITS 24U
#endif
#define MEMO_WAYS 4U
#define MEMO_LOCK_COUNT 4096U
#define LOW_BITS 16U
#define LOW_SIZE (UINT32_C(1) << LOW_BITS)
#define HIGH_BITS (MAX_N - LOW_BITS)
#define HIGH_SIZE (UINT32_C(1) << HIGH_BITS)
#define MAX_SUM (MAX_N * (MAX_N + 1U) / 2U)
#define REACH_WORDS ((MAX_SUM + 64U) / 64U)
#define BFILE_NAME "b399244_01.txt"

typedef struct {
    uint64_t low;
    uint64_t high;
} PrimeMask;

typedef struct {
    _Atomic uint8_t *status;
    uint32_t *masks;
    PrimeMask *used_primes;
    uint64_t *values;
    size_t capacity;
    _Atomic size_t size;
    bool bounded;
    pthread_mutex_t *locks;
    size_t lock_count;
    _Atomic uint64_t victim_counter;
} ConcurrentMemo;

typedef struct {
    ConcurrentMemo memo;
    _Atomic uint64_t computed_states;
    _Atomic uint64_t nonzero_states;
    _Atomic uint64_t pruned_states;
    _Atomic uint64_t wait_count;
    unsigned thread_count;
    unsigned n;
    uint16_t low_sum[LOW_SIZE];
    uint16_t high_sum[HIGH_SIZE];
    PrimeMask prime_bit[MAX_SUM + 1U];
    PrimeMask relevant_primes[MAX_SUM + 1U];
    uint16_t next_prime[MAX_SUM + 2U];
    unsigned primes[128];
    unsigned prime_count;
} Context;

typedef struct {
    Context *context;
    uint32_t *mitm_grouped[MAX_N];
    size_t mitm_capacity[MAX_N];
} Worker;

typedef struct {
    size_t index;
    uint32_t mask;
    PrimeMask used_primes;
} MemoToken;

typedef struct {
    uint32_t block_rest;
    uint16_t block_sum;
} RootTask;

_Static_assert(sizeof(RootTask) <= 8U,
               "RootTask must remain compact for n=28");

static const uint64_t known[KNOWN_N + 1U] = {
    UINT64_C(1), UINT64_C(0), UINT64_C(1), UINT64_C(0),
    UINT64_C(3), UINT64_C(4), UINT64_C(10), UINT64_C(24),
    UINT64_C(67), UINT64_C(145), UINT64_C(647), UINT64_C(2350),
    UINT64_C(8756), UINT64_C(33386), UINT64_C(102684),
    UINT64_C(611265), UINT64_C(2322253), UINT64_C(11765298),
    UINT64_C(58632351), UINT64_C(351652531), UINT64_C(2054333372),
    UINT64_C(9598979247), UINT64_C(62577811346)
};

static _Noreturn void die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static unsigned parse_n(const char *text)
{
    errno = 0;
    char *end = NULL;
    const uintmax_t value = strtoumax(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' || value > MAX_N) {
        fprintf(stderr, "error: n must be in 0..%u: %s\n", MAX_N, text);
        exit(EXIT_FAILURE);
    }
    return (unsigned)value;
}

static unsigned parse_threads(const char *text)
{
    errno = 0;
    char *end = NULL;
    const uintmax_t value = strtoumax(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' ||
        value == 0 || value > 64U) {
        fprintf(stderr, "error: threads must be in 1..64: %s\n", text);
        exit(EXIT_FAILURE);
    }
    return (unsigned)value;
}

static unsigned default_thread_count(void)
{
    const long detected = sysconf(_SC_NPROCESSORS_ONLN);
    if (detected <= 0) return 1U;
    return detected > 8 ? 8U : (unsigned)detected;
}

static unsigned highest_bit_index(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return 31U - (unsigned)__builtin_clz(mask);
#else
    unsigned index = 0;
    while (mask >>= 1U) ++index;
    return index;
#endif
}

static unsigned bit_count(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return (unsigned)__builtin_popcount(mask);
#else
    unsigned count = 0;
    while (mask != 0) {
        mask &= mask - 1U;
        ++count;
    }
    return count;
#endif
}

static PrimeMask prime_mask_bit(unsigned index)
{
    PrimeMask result = {0, 0};
    if (index < 64U)
        result.low = UINT64_C(1) << index;
    else
        result.high = UINT64_C(1) << (index - 64U);
    return result;
}

static bool prime_mask_has(PrimeMask mask, unsigned index)
{
    return index < 64U
        ? (mask.low & (UINT64_C(1) << index)) != 0
        : (mask.high & (UINT64_C(1) << (index - 64U))) != 0;
}

static bool prime_mask_equal(PrimeMask left, PrimeMask right)
{
    return left.low == right.low && left.high == right.high;
}

static bool prime_mask_is_zero(PrimeMask mask)
{
    return mask.low == 0 && mask.high == 0;
}

static bool prime_mask_intersects(PrimeMask left, PrimeMask right)
{
    return ((left.low & right.low) | (left.high & right.high)) != 0;
}

static PrimeMask prime_mask_or(PrimeMask left, PrimeMask right)
{
    PrimeMask result = {left.low | right.low, left.high | right.high};
    return result;
}

static PrimeMask prime_mask_and(PrimeMask left, PrimeMask right)
{
    PrimeMask result = {left.low & right.low, left.high & right.high};
    return result;
}

static uint16_t subset_sum(const Context *context, uint32_t mask)
{
    return (uint16_t)(context->low_sum[mask & (LOW_SIZE - 1U)] +
                      context->high_sum[mask >> LOW_BITS]);
}

static uint64_t hash_key(uint64_t key)
{
    key ^= key >> 30U;
    key *= UINT64_C(0xbf58476d1ce4e5b9);
    key ^= key >> 27U;
    key *= UINT64_C(0x94d049bb133111eb);
    key ^= key >> 31U;
    return key;
}

static uint64_t state_hash(uint32_t mask, PrimeMask used_primes)
{
    return hash_key(used_primes.low ^ hash_key(used_primes.high) ^
                    hash_key((uint64_t)mask + UINT64_C(0x9e3779b97f4a7c15)));
}

static bool memo_claim(Context *context, uint32_t mask,
                       PrimeMask used_primes, uint64_t *value,
                       MemoToken *token)
{
    ConcurrentMemo *memo = &context->memo;
    const uint64_t hash = state_hash(mask, used_primes);
    if (memo->bounded) {
        const size_t set_count = memo->capacity / MEMO_WAYS;
        const size_t base = ((size_t)hash & (set_count - 1U)) * MEMO_WAYS;
        pthread_mutex_t *lock =
            &memo->locks[(base / MEMO_WAYS) & (memo->lock_count - 1U)];
        const int lock_error = pthread_mutex_lock(lock);
        if (lock_error != 0) {
            fprintf(stderr, "error: pthread_mutex_lock: %s\n",
                    strerror(lock_error));
            exit(EXIT_FAILURE);
        }
        for (size_t way = 0; way < MEMO_WAYS; ++way) {
            const size_t candidate = base + way;
            if (atomic_load_explicit(&memo->status[candidate],
                                     memory_order_relaxed) == MEMO_COMPLETE &&
                memo->masks[candidate] == mask &&
                prime_mask_equal(memo->used_primes[candidate],
                                 used_primes)) {
                *value = memo->values[candidate];
                const int unlock_error = pthread_mutex_unlock(lock);
                if (unlock_error != 0) {
                    fprintf(stderr, "error: pthread_mutex_unlock: %s\n",
                            strerror(unlock_error));
                    exit(EXIT_FAILURE);
                }
                return false;
            }
        }
        const int unlock_error = pthread_mutex_unlock(lock);
        if (unlock_error != 0) {
            fprintf(stderr, "error: pthread_mutex_unlock: %s\n",
                    strerror(unlock_error));
            exit(EXIT_FAILURE);
        }
        token->index = base;
        token->mask = mask;
        token->used_primes = used_primes;
        return true;
    }

    size_t index = (size_t)hash & (memo->capacity - 1U);
    for (size_t probes = 0; probes < memo->capacity; ++probes) {
        uint8_t status =
            atomic_load_explicit(&memo->status[index], memory_order_acquire);
        if (status == MEMO_RESERVED) {
            do {
                sched_yield();
                status = atomic_load_explicit(&memo->status[index],
                                              memory_order_acquire);
            } while (status == MEMO_RESERVED);
            continue;
        }
        if (status == MEMO_EMPTY) {
            uint8_t expected = MEMO_EMPTY;
            if (atomic_compare_exchange_weak_explicit(
                    &memo->status[index], &expected, MEMO_RESERVED,
                    memory_order_acq_rel, memory_order_acquire)) {
                memo->masks[index] = mask;
                memo->used_primes[index] = used_primes;
                atomic_store_explicit(&memo->status[index], MEMO_BUSY,
                                      memory_order_release);
                const size_t size =
                    atomic_fetch_add_explicit(&memo->size, 1,
                                              memory_order_relaxed) + 1U;
                if (size * 10U >= memo->capacity * 7U)
                    die("concurrent memo table exceeded 70% load");
                token->index = index;
                token->mask = mask;
                token->used_primes = used_primes;
                return true;
            }
            continue;
        }
        if (memo->masks[index] == mask &&
            prime_mask_equal(memo->used_primes[index], used_primes)) {
            if (status == MEMO_BUSY) {
                atomic_fetch_add_explicit(&context->wait_count, 1,
                                          memory_order_relaxed);
                unsigned spins = 0;
                do {
                    status = atomic_load_explicit(&memo->status[index],
                                                  memory_order_acquire);
                    if (++spins == 1024U && status == MEMO_BUSY) {
                        sched_yield();
                        spins = 0;
                    }
                } while (status == MEMO_BUSY);
            }
            if (status != MEMO_COMPLETE)
                die("invalid concurrent memo state");
            *value = memo->values[index];
            return false;
        }
        index = (index + 1U) & (memo->capacity - 1U);
    }
    die("concurrent memo table is full");
}

static void memo_publish(Context *context, const MemoToken *token,
                         uint64_t value)
{
    ConcurrentMemo *memo = &context->memo;
    if (memo->bounded) {
        const size_t set_count = memo->capacity / MEMO_WAYS;
        const size_t base =
            ((size_t)state_hash(token->mask, token->used_primes) &
             (set_count - 1U)) * MEMO_WAYS;
        pthread_mutex_t *lock =
            &memo->locks[(base / MEMO_WAYS) & (memo->lock_count - 1U)];
        const int lock_error = pthread_mutex_lock(lock);
        if (lock_error != 0) {
            fprintf(stderr, "error: pthread_mutex_lock: %s\n",
                    strerror(lock_error));
            exit(EXIT_FAILURE);
        }
        size_t target = SIZE_MAX;
        for (size_t way = 0; way < MEMO_WAYS; ++way) {
            const size_t candidate = base + way;
            const uint8_t status =
                atomic_load_explicit(&memo->status[candidate],
                                     memory_order_relaxed);
            if (status == MEMO_COMPLETE &&
                memo->masks[candidate] == token->mask &&
                prime_mask_equal(memo->used_primes[candidate],
                                 token->used_primes)) {
                target = candidate;
                break;
            }
            if (status == MEMO_EMPTY && target == SIZE_MAX)
                target = candidate;
        }
        bool added = false;
        if (target == SIZE_MAX) {
            const uint64_t victim =
                atomic_fetch_add_explicit(&memo->victim_counter, 1,
                                          memory_order_relaxed);
            target = base + (size_t)(victim % MEMO_WAYS);
        } else if (atomic_load_explicit(&memo->status[target],
                                        memory_order_relaxed) == MEMO_EMPTY) {
            added = true;
        }
        memo->masks[target] = token->mask;
        memo->used_primes[target] = token->used_primes;
        memo->values[target] = value;
        atomic_store_explicit(&memo->status[target], MEMO_COMPLETE,
                              memory_order_relaxed);
        if (added)
            atomic_fetch_add_explicit(&memo->size, 1,
                                      memory_order_relaxed);
        const int unlock_error = pthread_mutex_unlock(lock);
        if (unlock_error != 0) {
            fprintf(stderr, "error: pthread_mutex_unlock: %s\n",
                    strerror(unlock_error));
            exit(EXIT_FAILURE);
        }
    } else {
        memo->values[token->index] = value;
        atomic_store_explicit(&memo->status[token->index],
                              MEMO_COMPLETE, memory_order_release);
    }
    atomic_fetch_add_explicit(&context->computed_states, 1,
                              memory_order_relaxed);
    if (value != 0)
        atomic_fetch_add_explicit(&context->nonzero_states, 1,
                                  memory_order_relaxed);
}

static bool unused_primes_can_sum(const Context *context,
                                  PrimeMask used_primes, unsigned sum)
{
    uint64_t reachable[REACH_WORDS];
    memset(reachable, 0, sizeof(reachable));
    reachable[0] = UINT64_C(1);
    for (unsigned i = 0; i < context->prime_count; ++i) {
        const unsigned prime = context->primes[i];
        if (prime > sum) break;
        if (prime_mask_has(used_primes, i)) continue;
        const unsigned word_shift = prime / 64U;
        const unsigned bit_shift = prime % 64U;
        for (unsigned word = REACH_WORDS; word-- > 0;) {
            const uint64_t source = reachable[word];
            if (source == 0) continue;
            const unsigned target = word + word_shift;
            if (target < REACH_WORDS)
                reachable[target] |= source << bit_shift;
            if (bit_shift != 0 && target + 1U < REACH_WORDS)
                reachable[target + 1U] |=
                    source >> (64U - bit_shift);
        }
    }
    return ((reachable[sum / 64U] >> (sum % 64U)) & UINT64_C(1)) != 0;
}

static PrimeMask attainable_prime_mask(const Context *context, uint32_t mask)
{
    uint64_t reachable[REACH_WORDS];
    memset(reachable, 0, sizeof(reachable));
    reachable[0] = UINT64_C(1);
    uint32_t copy = mask;
    while (copy != 0) {
        const uint32_t bit = copy & (0U - copy);
        copy ^= bit;
        const unsigned value = highest_bit_index(bit) + 1U;
        const unsigned word_shift = value / 64U;
        const unsigned bit_shift = value % 64U;
        for (unsigned word = REACH_WORDS; word-- > 0;) {
            const uint64_t source = reachable[word];
            if (source == 0) continue;
            const unsigned target = word + word_shift;
            if (target < REACH_WORDS)
                reachable[target] |= source << bit_shift;
            if (bit_shift != 0 && target + 1U < REACH_WORDS)
                reachable[target + 1U] |=
                    source >> (64U - bit_shift);
        }
    }
    PrimeMask result = {0, 0};
    for (unsigned i = 0; i < context->prime_count; ++i) {
        const unsigned prime = context->primes[i];
        if (((reachable[prime / 64U] >> (prime % 64U)) & UINT64_C(1)) != 0)
            result = prime_mask_or(result, prime_mask_bit(i));
    }
    return result;
}

static uint32_t *mitm_workspace(Worker *worker, unsigned depth,
                                size_t needed)
{
    if (depth >= MAX_N) die("internal recursion depth overflow");
    if (worker->mitm_capacity[depth] < needed) {
        if (needed > SIZE_MAX / sizeof(*worker->mitm_grouped[depth]))
            die("meet-in-the-middle workspace is too large");
        uint32_t *replacement =
            realloc(worker->mitm_grouped[depth],
                    needed * sizeof(*worker->mitm_grouped[depth]));
        if (replacement == NULL)
            die("could not allocate meet-in-the-middle workspace");
        worker->mitm_grouped[depth] = replacement;
        worker->mitm_capacity[depth] = needed;
    }
    return worker->mitm_grouped[depth];
}

static void checked_add(uint64_t *total, uint64_t addend)
{
    if (UINT64_MAX - *total < addend)
        die("uint64_t overflow while counting partitions");
    *total += addend;
}

static uint64_t count_partitions(Worker *worker, uint32_t mask,
                                 PrimeMask used_primes, unsigned depth)
{
    if (mask == 0) return 1U;
    Context *context = worker->context;
    const unsigned remaining_sum = subset_sum(context, mask);
    used_primes = prime_mask_and(
        used_primes,
        prime_mask_and(context->relevant_primes[remaining_sum],
                       attainable_prime_mask(context, mask)));

    uint64_t memoized;
    MemoToken token;
    if (!memo_claim(context, mask, used_primes, &memoized, &token))
        return memoized;

    if (!unused_primes_can_sum(context, used_primes, remaining_sum)) {
        atomic_fetch_add_explicit(&context->pruned_states, 1,
                                  memory_order_relaxed);
        memo_publish(context, &token, 0U);
        return 0U;
    }

    const unsigned pivot_index = highest_bit_index(mask);
    const uint32_t pivot = UINT32_C(1) << pivot_index;
    const uint32_t rest = mask ^ pivot;
    const unsigned pivot_value = pivot_index + 1U;
    uint64_t total = 0;

    const unsigned rest_size = bit_count(rest);
    if (rest_size >= MITM_MIN_REST_SIZE) {
        uint32_t low_elements = 0;
        uint32_t high_elements = 0;
        uint32_t copy = rest;
        for (unsigned i = 0; copy != 0; ++i) {
            const uint32_t bit = copy & (0U - copy);
            copy ^= bit;
            if (i < rest_size / 2U)
                low_elements |= bit;
            else
                high_elements |= bit;
        }

        const unsigned high_count = bit_count(high_elements);
        const size_t high_subset_count = (size_t)1U << high_count;
        const unsigned maximum_high_sum =
            subset_sum(context, high_elements);
        uint32_t counts[MAX_SUM + 1U];
        uint32_t offsets[MAX_SUM + 2U];
        memset(counts, 0,
               (maximum_high_sum + 1U) * sizeof(*counts));
        uint32_t high = high_elements;
        for (;;) {
            ++counts[subset_sum(context, high)];
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }
        offsets[0] = 0;
        for (unsigned sum = 0; sum <= maximum_high_sum; ++sum)
            offsets[sum + 1U] = offsets[sum] + counts[sum];

        uint32_t *grouped =
            mitm_workspace(worker, depth, high_subset_count);
        uint32_t cursor[MAX_SUM + 1U];
        memcpy(cursor, offsets,
               (maximum_high_sum + 1U) * sizeof(*cursor));
        high = high_elements;
        for (;;) {
            const unsigned sum = subset_sum(context, high);
            grouped[cursor[sum]++] = high;
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }

        const unsigned maximum_block_sum =
            pivot_value + subset_sum(context, rest);
        uint32_t low = low_elements;
        for (;;) {
            const unsigned low_value = subset_sum(context, low);
            for (unsigned target =
                     context->next_prime[pivot_value + low_value];
                 target <= maximum_block_sum;
                 target = context->next_prime[target + 1U]) {
                const PrimeMask prime_mask = context->prime_bit[target];
                if (prime_mask_intersects(used_primes, prime_mask)) continue;
                const unsigned high_value =
                    target - pivot_value - low_value;
                if (high_value > maximum_high_sum) continue;
                for (uint32_t i = offsets[high_value];
                     i < offsets[high_value + 1U]; ++i) {
                    const uint32_t block_rest = low | grouped[i];
                    checked_add(&total,
                                count_partitions(worker,
                                                 rest ^ block_rest,
                                                 prime_mask_or(used_primes,
                                                               prime_mask),
                                                 depth + 1U));
                }
            }
            if (low == 0) break;
            low = (low - 1U) & low_elements;
        }
    } else {
        uint32_t block_rest = rest;
        for (;;) {
            const unsigned block_sum =
                pivot_value + subset_sum(context, block_rest);
            const PrimeMask prime_mask = context->prime_bit[block_sum];
            if (!prime_mask_is_zero(prime_mask) &&
                !prime_mask_intersects(used_primes, prime_mask))
                checked_add(&total,
                            count_partitions(worker, rest ^ block_rest,
                                             prime_mask_or(used_primes,
                                                           prime_mask),
                                             depth + 1U));
            if (block_rest == 0) break;
            block_rest = (block_rest - 1U) & rest;
        }
    }

    memo_publish(context, &token, total);
    return total;
}

static void initialize_element_sums(Context *context)
{
    context->low_sum[0] = 0;
    for (uint32_t mask = 1; mask < LOW_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        context->low_sum[mask] =
            (uint16_t)(context->low_sum[mask ^ bit] +
                       highest_bit_index(bit) + 1U);
    }

    context->high_sum[0] = 0;
    for (uint32_t mask = 1; mask < HIGH_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        context->high_sum[mask] =
            (uint16_t)(context->high_sum[mask ^ bit] + LOW_BITS +
                       highest_bit_index(bit) + 1U);
    }
}

static void initialize_primes(Context *context)
{
    bool is_prime[MAX_SUM + 1U];
    memset(is_prime, 0, sizeof(is_prime));
    for (unsigned value = 2; value <= MAX_SUM; ++value)
        is_prime[value] = true;
    for (unsigned divisor = 2; divisor <= MAX_SUM / divisor; ++divisor) {
        if (!is_prime[divisor]) continue;
        for (unsigned composite = divisor * divisor;
             composite <= MAX_SUM; composite += divisor)
            is_prime[composite] = false;
    }

    for (unsigned value = 2; value <= MAX_SUM; ++value) {
        if (!is_prime[value]) continue;
        if (context->prime_count == 128U)
            die("more than 128 prime sums require a wider used-prime mask");
        const unsigned index = context->prime_count++;
        context->primes[index] = value;
        context->prime_bit[value] = prime_mask_bit(index);
    }

    PrimeMask relevant = {0, 0};
    for (unsigned value = 0; value <= MAX_SUM; ++value) {
        relevant = prime_mask_or(relevant, context->prime_bit[value]);
        context->relevant_primes[value] = relevant;
    }

    unsigned next = MAX_SUM + 1U;
    context->next_prime[MAX_SUM + 1U] = (uint16_t)next;
    for (unsigned value = MAX_SUM + 1U; value-- > 0;) {
        if (is_prime[value]) next = value;
        context->next_prime[value] = (uint16_t)next;
    }
}

static size_t memo_capacity_for_n(unsigned n)
{
    if (n >= BOUNDED_MEMO_MIN_N)
        return (size_t)1U << BOUNDED_MEMO_BITS;
    unsigned bits;
    if (n <= 13U)
        bits = 16U;
    else if (n <= 16U)
        bits = 18U;
    else
        bits = n + 3U;
    return (size_t)1U << bits;
}

static void destroy_memo_locks(ConcurrentMemo *memo)
{
    for (size_t i = 0; i < memo->lock_count; ++i) {
        const int error = pthread_mutex_destroy(&memo->locks[i]);
        if (error != 0) {
            fprintf(stderr, "error: pthread_mutex_destroy: %s\n",
                    strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    free(memo->locks);
    memo->locks = NULL;
    memo->lock_count = 0;
}

static void context_prepare_n(Context *context, unsigned n)
{
    const size_t capacity = memo_capacity_for_n(n);
    if (capacity > SIZE_MAX / sizeof(*context->memo.status) ||
        capacity > SIZE_MAX / sizeof(*context->memo.masks) ||
        capacity > SIZE_MAX / sizeof(*context->memo.used_primes) ||
        capacity > SIZE_MAX / sizeof(*context->memo.values))
        die("concurrent memo allocation size overflow");
    destroy_memo_locks(&context->memo);
    free(context->memo.status);
    free(context->memo.masks);
    free(context->memo.used_primes);
    free(context->memo.values);
    context->memo.status = calloc(capacity, sizeof(*context->memo.status));
    context->memo.masks = malloc(capacity * sizeof(*context->memo.masks));
    context->memo.used_primes =
        malloc(capacity * sizeof(*context->memo.used_primes));
    context->memo.values = malloc(capacity * sizeof(*context->memo.values));
    if (context->memo.status == NULL || context->memo.masks == NULL ||
        context->memo.used_primes == NULL || context->memo.values == NULL)
        die("could not allocate concurrent memo table");
    context->memo.capacity = capacity;
    context->memo.bounded = n >= BOUNDED_MEMO_MIN_N;
    if (context->memo.bounded) {
        context->memo.lock_count = MEMO_LOCK_COUNT;
        context->memo.locks =
            malloc(context->memo.lock_count * sizeof(*context->memo.locks));
        if (context->memo.locks == NULL)
            die("could not allocate bounded-memo locks");
        for (size_t i = 0; i < context->memo.lock_count; ++i) {
            const int error = pthread_mutex_init(&context->memo.locks[i],
                                                 NULL);
            if (error != 0) {
                fprintf(stderr, "error: pthread_mutex_init: %s\n",
                        strerror(error));
                exit(EXIT_FAILURE);
            }
        }
    }
    atomic_store_explicit(&context->memo.size, 0, memory_order_relaxed);
    atomic_store_explicit(&context->memo.victim_counter, 0,
                          memory_order_relaxed);
    context->n = n;
    if (n >= 18U) {
        fprintf(stderr, "preparing n=%u: %s memo with %zu slots\n",
                n, context->memo.bounded ? "bounded" : "exact", capacity);
        if (fflush(stderr) == EOF)
            die("could not flush memo preparation output");
    }
}

static Context *context_create(unsigned thread_count)
{
    Context *context = calloc(1, sizeof(*context));
    if (context == NULL) die("could not allocate the DP context");
    context->thread_count = thread_count;
    initialize_element_sums(context);
    initialize_primes(context);
    return context;
}

static void worker_destroy(Worker *worker)
{
    for (unsigned i = 0; i < MAX_N; ++i)
        free(worker->mitm_grouped[i]);
}

static void context_destroy(Context *context)
{
    destroy_memo_locks(&context->memo);
    free(context->memo.status);
    free(context->memo.masks);
    free(context->memo.used_primes);
    free(context->memo.values);
    free(context);
}

typedef struct {
    Context *context;
    RootTask *tasks;
    size_t task_count;
    uint32_t rest;
    _Atomic size_t next_task;
    _Atomic size_t completed_tasks;
    _Atomic bool stop_progress;
    Worker *workers;
    uint64_t *results;
    uint64_t initial_state_count;
    double start_time;
    unsigned term;
} RootQueue;

typedef struct {
    RootQueue *queue;
    unsigned worker_index;
} ThreadArgument;

static double monotonic_seconds(void)
{
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) != 0)
        die("could not read the monotonic clock");
    return (double)now.tv_sec + (double)now.tv_nsec / 1000000000.0;
}

static void report_progress(const RootQueue *queue, bool finished)
{
    const size_t completed =
        atomic_load_explicit(&queue->completed_tasks,
                             memory_order_relaxed);
    const uint64_t states =
        atomic_load_explicit(&queue->context->computed_states,
                             memory_order_relaxed);
    const double percent = queue->task_count == 0 ? 100.0
        : 100.0 * (double)completed / (double)queue->task_count;
    fprintf(stderr,
            "progress n=%u: root jobs %zu/%zu (%.1f%%), "
            "new evaluations=%" PRIu64 ", elapsed=%.1fs%s\n",
            queue->term, completed, queue->task_count, percent,
            states - queue->initial_state_count,
            monotonic_seconds() - queue->start_time,
            finished ? ", done" : "");
    if (fflush(stderr) == EOF) die("could not flush progress output");
}

static void *progress_worker(void *opaque)
{
    RootQueue *queue = opaque;
    double next_report = queue->start_time + PROGRESS_INTERVAL_SECONDS;
    const struct timespec pause = {0, PROGRESS_POLL_NANOSECONDS};
    while (!atomic_load_explicit(&queue->stop_progress,
                                 memory_order_acquire)) {
        (void)nanosleep(&pause, NULL);
        const double now = monotonic_seconds();
        if (now >= next_report &&
            !atomic_load_explicit(&queue->stop_progress,
                                  memory_order_acquire)) {
            report_progress(queue, false);
            do {
                next_report += PROGRESS_INTERVAL_SECONDS;
            } while (next_report <= now);
        }
    }
    return NULL;
}

static RootTask *build_root_tasks(const Context *context, uint32_t mask,
                                  size_t *result_count)
{
    const unsigned pivot_index = highest_bit_index(mask);
    const uint32_t pivot = UINT32_C(1) << pivot_index;
    const uint32_t rest = mask ^ pivot;
    const unsigned pivot_value = pivot_index + 1U;
    size_t total = 0;
    uint32_t block_rest = rest;
    for (;;) {
        const unsigned block_sum =
            pivot_value + subset_sum(context, block_rest);
        if (!prime_mask_is_zero(context->prime_bit[block_sum])) ++total;
        if (block_rest == 0) break;
        block_rest = (block_rest - 1U) & rest;
    }
    if (total > SIZE_MAX / sizeof(RootTask))
        die("root task allocation size overflow");
    RootTask *tasks = total == 0 ? NULL : malloc(total * sizeof(*tasks));
    if (total != 0 && tasks == NULL)
        die("could not allocate root task list");
    size_t used = 0;
    block_rest = rest;
    for (;;) {
        const unsigned block_sum =
            pivot_value + subset_sum(context, block_rest);
        const PrimeMask prime_mask = context->prime_bit[block_sum];
        if (!prime_mask_is_zero(prime_mask)) {
            tasks[used].block_rest = block_rest;
            tasks[used].block_sum = (uint16_t)block_sum;
            ++used;
        }
        if (block_rest == 0) break;
        block_rest = (block_rest - 1U) & rest;
    }
    if (used != total) die("internal root task count mismatch");
    *result_count = total;
    return tasks;
}

static void *root_worker(void *opaque)
{
    ThreadArgument *argument = opaque;
    RootQueue *queue = argument->queue;
    Worker *worker = &queue->workers[argument->worker_index];
    uint64_t total = 0;
    for (;;) {
        const size_t begin =
            atomic_fetch_add_explicit(&queue->next_task, TASK_CHUNK,
                                      memory_order_relaxed);
        if (begin >= queue->task_count) break;
        size_t end = begin + TASK_CHUNK;
        if (end > queue->task_count) end = queue->task_count;
        for (size_t i = begin; i < end; ++i) {
            const RootTask task = queue->tasks[i];
            const PrimeMask prime_mask =
                queue->context->prime_bit[task.block_sum];
            checked_add(&total,
                        count_partitions(worker,
                                         queue->rest ^ task.block_rest,
                                         prime_mask, 0U));
        }
        atomic_fetch_add_explicit(&queue->completed_tasks, end - begin,
                                  memory_order_relaxed);
    }
    queue->results[argument->worker_index] = total;
    return NULL;
}

static uint64_t count_full(Context *context, uint32_t mask)
{
    if (mask == 0) return 1U;
    const PrimeMask empty_primes = {0, 0};
    Worker serial_worker;
    memset(&serial_worker, 0, sizeof(serial_worker));
    serial_worker.context = context;
    const unsigned term = bit_count(mask);
    if (term < PARALLEL_MIN_N || context->thread_count == 1U) {
        const uint64_t result =
            count_partitions(&serial_worker, mask, empty_primes, 0U);
        worker_destroy(&serial_worker);
        return result;
    }

    uint64_t memoized;
    MemoToken root_token;
    if (!memo_claim(context, mask, empty_primes, &memoized, &root_token)) {
        worker_destroy(&serial_worker);
        return memoized;
    }
    if (!unused_primes_can_sum(context, empty_primes,
                               subset_sum(context, mask))) {
        atomic_fetch_add_explicit(&context->pruned_states, 1,
                                  memory_order_relaxed);
        memo_publish(context, &root_token, 0U);
        worker_destroy(&serial_worker);
        return 0U;
    }

    size_t task_count = 0;
    RootTask *tasks = build_root_tasks(context, mask, &task_count);
    unsigned thread_count = context->thread_count;
    if (task_count != 0 && thread_count > task_count)
        thread_count = (unsigned)task_count;
    if (thread_count == 0) thread_count = 1U;
    RootQueue queue;
    memset(&queue, 0, sizeof(queue));
    queue.context = context;
    queue.tasks = tasks;
    queue.task_count = task_count;
    queue.term = term;
    queue.initial_state_count =
        atomic_load_explicit(&context->computed_states,
                             memory_order_relaxed);
    queue.start_time = monotonic_seconds();
    queue.rest = mask ^ (UINT32_C(1) << highest_bit_index(mask));
    queue.workers = calloc(thread_count, sizeof(*queue.workers));
    queue.results = calloc(thread_count, sizeof(*queue.results));
    ThreadArgument *arguments =
        calloc(thread_count, sizeof(*arguments));
    pthread_t *threads = thread_count > 1U
        ? calloc(thread_count - 1U, sizeof(*threads)) : NULL;
    pthread_t progress_thread;
    const bool show_progress = term >= PROGRESS_MIN_N;
    if (queue.workers == NULL || queue.results == NULL ||
        arguments == NULL || (thread_count > 1U && threads == NULL))
        die("could not allocate root worker data");
    for (unsigned i = 0; i < thread_count; ++i) {
        queue.workers[i].context = context;
        arguments[i].queue = &queue;
        arguments[i].worker_index = i;
    }
    if (show_progress) {
        report_progress(&queue, false);
        const int error =
            pthread_create(&progress_thread, NULL, progress_worker, &queue);
        if (error != 0) {
            fprintf(stderr, "error: pthread_create: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    for (unsigned i = 1; i < thread_count; ++i) {
        const int error =
            pthread_create(&threads[i - 1U], NULL, root_worker,
                           &arguments[i]);
        if (error != 0) {
            fprintf(stderr, "error: pthread_create: %s\n",
                    strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    root_worker(&arguments[0]);
    for (unsigned i = 1; i < thread_count; ++i) {
        const int error = pthread_join(threads[i - 1U], NULL);
        if (error != 0) {
            fprintf(stderr, "error: pthread_join: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    if (show_progress) {
        atomic_store_explicit(&queue.stop_progress, true,
                              memory_order_release);
        const int error = pthread_join(progress_thread, NULL);
        if (error != 0) {
            fprintf(stderr, "error: pthread_join: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }

    uint64_t result = 0;
    for (unsigned i = 0; i < thread_count; ++i) {
        checked_add(&result, queue.results[i]);
        worker_destroy(&queue.workers[i]);
    }
    memo_publish(context, &root_token, result);
    if (show_progress) report_progress(&queue, true);
    free(threads);
    free(arguments);
    free(queue.results);
    free(queue.workers);
    free(tasks);
    worker_destroy(&serial_worker);
    return result;
}

static FILE *open_bfile(void)
{
    FILE *stream = fopen(BFILE_NAME, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: could not create %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
    return stream;
}

static void write_bfile_term(FILE *stream, unsigned n, uint64_t value)
{
    if (fprintf(stream, "%u %" PRIu64 "\n", n, value) < 0 ||
        fflush(stream) != 0) {
        fprintf(stderr, "error: could not write %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
    const int descriptor = fileno(stream);
    if (descriptor < 0 || fsync(descriptor) != 0) {
        fprintf(stderr, "error: could not synchronize %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void close_bfile(FILE *stream)
{
    if (fclose(stream) != 0) {
        fprintf(stderr, "error: could not close %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void usage(FILE *stream, const char *program)
{
    fprintf(stream,
            "Usage: %s [--upto N | --target N] [--threads T] "
            "[--self-test] [--stats]\n"
            "  --upto N     print a(0)..a(N), 0 <= N <= %u (default %u)\n"
            "  --target N   print only a(N)\n"
            "               n<=22 uses an exact full-key memo; n>=23 uses\n"
            "               a fixed-size exact-result cache with eviction\n"
            "               peak storage is about 1 GiB (near n=22)\n"
            "  --threads T  use 1..64 workers (default: up to 8 CPUs)\n"
            "  --self-test  compare computed terms with regression values\n"
            "  --stats      report memoized and pruned state counts\n"
            "  Progress is reported every 60 seconds for n>=23.\n"
            "  Results are synchronized to " BFILE_NAME
            " after every term.\n"
            "  --help       show this help\n",
            program, MAX_N, DEFAULT_N);
}

int main(int argc, char **argv)
{
    unsigned n = DEFAULT_N;
    unsigned thread_count = default_thread_count();
    bool target_only = false;
    bool self_test = false;
    bool stats = false;

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--upto") == 0) {
            if (++i == argc) die("--upto requires an argument");
            n = parse_n(argv[i]);
            target_only = false;
        } else if (strcmp(argv[i], "--target") == 0) {
            if (++i == argc) die("--target requires an argument");
            n = parse_n(argv[i]);
            target_only = true;
        } else if (strcmp(argv[i], "--threads") == 0) {
            if (++i == argc) die("--threads requires an argument");
            thread_count = parse_threads(argv[i]);
        } else if (strcmp(argv[i], "--self-test") == 0) {
            self_test = true;
        } else if (strcmp(argv[i], "--stats") == 0) {
            stats = true;
        } else if (strcmp(argv[i], "--help") == 0 ||
                   strcmp(argv[i], "-h") == 0) {
            usage(stdout, argv[0]);
            return EXIT_SUCCESS;
        } else {
            fprintf(stderr, "error: unknown argument: %s\n", argv[i]);
            usage(stderr, argv[0]);
            return EXIT_FAILURE;
        }
    }

    Context *context = context_create(thread_count);
    FILE *bfile = open_bfile();
    const unsigned first = target_only ? n : 0U;
    for (unsigned k = first; k <= n; ++k) {
        context_prepare_n(context, k);
        const uint32_t mask =
            k == 0 ? 0U : (UINT32_C(1) << k) - 1U;
        const uint64_t value = count_full(context, mask);
        if (self_test && k <= KNOWN_N && value != known[k]) {
            fprintf(stderr,
                    "self-test failed at n=%u: got %" PRIu64
                    ", expected %" PRIu64 "\n",
                    k, value, known[k]);
            close_bfile(bfile);
            context_destroy(context);
            return EXIT_FAILURE;
        }
        write_bfile_term(bfile, k, value);
        printf("%u %" PRIu64 "\n", k, value);
        if (fflush(stdout) == EOF) die("could not flush sequence output");
    }
    if (self_test) {
        if (target_only && n > KNOWN_N) {
            fprintf(stderr,
                    "no stored regression value at n=%u "
                    "(known values end at n=%u)\n",
                    n, KNOWN_N);
        } else {
            const unsigned tested = n < KNOWN_N ? n : KNOWN_N;
            fprintf(stderr, "self-test passed through known n=%u\n",
                    tested);
        }
    }
    if (stats)
        fprintf(stderr,
                "memoized states: %" PRIu64 ", nonzero: %" PRIu64
                ", pruned: %" PRIu64 ", waits: %" PRIu64
                ", table: %zu/%zu\n",
                atomic_load_explicit(&context->computed_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&context->nonzero_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&context->pruned_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&context->wait_count,
                                     memory_order_relaxed),
                atomic_load_explicit(&context->memo.size,
                                     memory_order_relaxed),
                context->memo.capacity);
    close_bfile(bfile);
    context_destroy(context);
    return EXIT_SUCCESS;
}
