/*
 * A322308 -- exact meet-in-the-middle evaluator.
 *
 * Count permutations sigma of {1,...,n} satisfying
 *
 *   |sigma(i+j)-sigma(i)| >= 5,
 *             1 <= j <= 4,  1 <= i <= n-j.
 *
 * This program differs from 322308_01.c at the whole-permutation level.
 * Program 01 propagates prefixes to length n; program 02 stops at the middle
 * and joins two independently counted half paths.  Both use the necessary
 * width-four local state, but their completion algorithms are different.
 *
 * Let P_k(S,a,b,c,d) count valid orderings of S ending a,b,c,d. Split a full
 * permutation as (...,a,b,c,d | e,f,g,h,...). Reversing the right half gives
 * R(e,f,g,h)=P_r(T,h,g,f,e). Exactly ten inequalities cross the split:
 *
 *   d~e,d~f,d~g,d~h, c~e,c~f,c~g, b~e,b~f, a~e,
 *                                         where x~y means |x-y|>=5.
 *
 * Each half table is expanded from complement-orbit representatives into
 * exact endpoint records and sorted by its used-value mask.  Only an
 * actually present left mask S and its actually present complementary right
 * mask T are joined, and only endpoint quadruples stored in those groups are
 * tested against the ten inequalities.  This sparse grouped join avoids the
 * enormous n^8 Cartesian endpoint space.
 * For even n, S and T give reversal-paired full permutations, so only
 * S<T is joined and the result is doubled.
 *
 * Half paths are generated by sparse subset DP, but only through length
 * ceil(n/2).  Two hash layers are used.  Before a growing layer is filled,
 * its obsolete buffer is released and a damped estimate from the preceding
 * layer sizes is reserved; unlike incremental growth, this normally avoids
 * holding old and new large buffers simultaneously.
 *
 * Value complementation v -> n-1-v is also used.  A hash slot stores the
 * combined count of the two reflected states. Every ordered-quadruple state
 * has orbit size two, so lookup divides the stored value by two to recover
 * P_k(S,a,b,c,d). --no-symmetry disables this optimization; --check compares
 * the two versions on small n.
 *
 * Safety:
 *   - half-path counts and the final positive sum are bounded by n!;
 *   - 34! < 2^128, so unsigned 128-bit arithmetic is exact for n<=34;
 *   - additions, subtractions, products, key packing, table growth, and
 *     allocation sizes are checked anyway;
 *   - a main state slot is 16 bytes (key + low count word); nonzero high
 *     words alone occupy a separate sparse table, preserving exact 128-bit
 *     coefficients without paying 24 bytes for every hash slot;
 *   - --memory-mib is a hard budget for DP tables and endpoint records;
 *   - a range run flushes b322308_02_part.txt after each completed term
 *     and renames it atomically to b322308_02.txt only after success.
 *
 * The integer type is safe through n=34, but the exponential half-state
 * table normally sets a much smaller practical limit.
 *
 * Build:
 *
 *   clang -O3 -std=c11 -Wall -Wextra -Wpedantic \
 *     322308_02.c -o 322308_02
 *
 * Usage:
 *
 *   ./322308_02
 *   ./322308_02 --term 28 --memory-mib 2048
 *   ./322308_02 --upto 28 --memory-mib 2048
 *   ./322308_02 --no-symmetry --term 20
 *   ./322308_02 --check
 *
 * Reference:
 *   https://oeis.org/A322308
 */

#define _POSIX_C_SOURCE 200809L

#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#ifdef __APPLE__
#include <mach-o/dyld.h>
#endif

#if !defined(__SIZEOF_INT128__)
#error "322308_02 requires compiler support for unsigned __int128"
#endif

__extension__ typedef unsigned __int128 uint128_t;

#define SEQUENCE_OFFSET 0
#define DEFAULT_MAX_N 28
#define MAX_SUPPORTED_N 34
#define REFERENCE_MAX_N 28
#define OEIS_MAX_N 28
#define DEFAULT_CHECK_N 28
#define DIRECT_CHECK_MAX_N 10
#define SYMMETRY_CHECK_MAX_N 20
#define DEFAULT_MEMORY_MIB UINT64_C(1024)
#define MIN_MEMORY_MIB UINT64_C(16)
#define INITIAL_CAPACITY ((size_t)16)
#define LOAD_NUMERATOR ((size_t)3)
#define LOAD_DENOMINATOR ((size_t)4)
#define ENDPOINT_BITS 6U
#define ENDPOINT_MASK UINT64_C(63)
#define STATE_SHIFT (4U * ENDPOINT_BITS)

_Static_assert(MAX_SUPPORTED_N < 64,
               "the value-set mask must fit in uint64_t");
_Static_assert(MAX_SUPPORTED_N + STATE_SHIFT < 64,
               "the packed state key must fit in uint64_t");

/*
 * n=0..28 are from the OEIS b-file and are also regression values produced
 * by the independently completed full-prefix program 322308_01.c.
 */
static const char *const reference_terms[REFERENCE_MAX_N + 1] = {
    "1", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0",
    "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
    "0", "0", "0", "2", "128", "6320", "344872"
};

typedef struct {
    uint64_t low;
    uint64_t high;
} Count128;

typedef struct {
    uint64_t key_plus_one;
    uint64_t count_low;
} StateSlot;

typedef struct {
    uint64_t key_plus_one;
    uint64_t count_high;
} HighSlot;

_Static_assert(sizeof(StateSlot) == 16U, "StateSlot must stay compact");
_Static_assert(sizeof(HighSlot) == 16U, "HighSlot must stay compact");

typedef struct {
    size_t limit;
    size_t in_use;
    size_t peak;
} MemoryBudget;

typedef struct {
    StateSlot *slots;
    size_t capacity;
    size_t size;
    HighSlot *high_slots;
    size_t high_capacity;
    size_t high_size;
    MemoryBudget *budget;
} StateMap;

typedef struct {
    uint64_t prefix_transitions;
    uint64_t split_subsets;
    uint64_t joined_endpoint_pairs;
    size_t left_states;
    size_t right_states;
    size_t peak_bytes;
    double build_seconds;
    double join_seconds;
    double total_seconds;
} MitmStats;

typedef enum {
    RUN_UPTO,
    RUN_TERM,
    RUN_CHECK
} RunMode;

static void die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static double monotonic_seconds(void)
{
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) != 0) {
        die("clock_gettime failed");
    }
    return (double)now.tv_sec + (double)now.tv_nsec / 1000000000.0;
}

static size_t checked_product_size(size_t left, size_t right)
{
    if (left != 0U && right > SIZE_MAX / left) {
        die("allocation size overflow");
    }
    return left * right;
}

static int parse_n(const char *text, const char *label)
{
    char *end = NULL;
    errno = 0;
    long value = strtol(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' ||
        value < SEQUENCE_OFFSET || value > MAX_SUPPORTED_N) {
        fprintf(stderr, "error: %s must be in %d..%d: %s\n",
                label, SEQUENCE_OFFSET, MAX_SUPPORTED_N, text);
        exit(EXIT_FAILURE);
    }
    return (int)value;
}

static uint64_t parse_memory_mib(const char *text)
{
    char *end = NULL;
    errno = 0;
    unsigned long long value = strtoull(text, &end, 10);
    uint64_t maximum = (uint64_t)(SIZE_MAX / (size_t)UINT64_C(1048576));
    if (errno != 0 || end == text || *end != '\0' ||
        value < MIN_MEMORY_MIB || value > maximum) {
        fprintf(stderr,
                "error: MEMORY_MIB must be in %" PRIu64 "..%" PRIu64
                ": %s\n",
                MIN_MEMORY_MIB, maximum, text);
        exit(EXIT_FAILURE);
    }
    return (uint64_t)value;
}

static Count128 count_zero(void)
{
    Count128 result = {0, 0};
    return result;
}

static Count128 count_from_u64(uint64_t value)
{
    Count128 result = {value, 0};
    return result;
}

static bool count_equal(Count128 left, Count128 right)
{
    return left.low == right.low && left.high == right.high;
}

static void count_add_to(Count128 *destination, Count128 addend)
{
    uint64_t old_low = destination->low;
    uint64_t new_low = old_low + addend.low;
    uint64_t carry = new_low < old_low ? UINT64_C(1) : UINT64_C(0);

    uint64_t old_high = destination->high;
    uint64_t new_high = old_high + addend.high;
    if (new_high < old_high) {
        die("unsigned 128-bit addition overflow");
    }
    uint64_t final_high = new_high + carry;
    if (final_high < new_high) {
        die("unsigned 128-bit addition overflow");
    }
    destination->low = new_low;
    destination->high = final_high;
}

static Count128 count_halve(Count128 value)
{
    if ((value.low & UINT64_C(1)) != 0) {
        die("internal odd reflected-orbit count");
    }
    Count128 result;
    result.low = (value.low >> 1U) | (value.high << 63U);
    result.high = value.high >> 1U;
    return result;
}

static uint128_t count_to_u128(Count128 value)
{
    return ((uint128_t)value.high << 64U) | (uint128_t)value.low;
}

static Count128 count_from_u128(uint128_t value)
{
    Count128 result = {(uint64_t)value, (uint64_t)(value >> 64U)};
    return result;
}

static Count128 count_multiply(Count128 left, Count128 right)
{
    uint128_t a = count_to_u128(left);
    uint128_t b = count_to_u128(right);
    uint128_t maximum = ~(uint128_t)0;
    if (a != 0 && b > maximum / a) {
        die("unsigned 128-bit multiplication overflow");
    }
    return count_from_u128(a * b);
}

static Count128 parse_count(const char *text)
{
    uint128_t value = 0;
    for (const unsigned char *p = (const unsigned char *)text;
         *p != '\0'; ++p) {
        if (*p < (unsigned char)'0' || *p > (unsigned char)'9') {
            die("invalid built-in decimal value");
        }
        unsigned digit = (unsigned)(*p - (unsigned char)'0');
        uint128_t maximum = ~(uint128_t)0;
        if (value > (maximum - (uint128_t)digit) / (uint128_t)10U) {
            die("built-in decimal value exceeds unsigned 128-bit range");
        }
        value = value * (uint128_t)10U + (uint128_t)digit;
    }
    return count_from_u128(value);
}

static int fprint_count(FILE *stream, Count128 count)
{
    char digits[40];
    size_t length = 0;
    uint128_t value = count_to_u128(count);
    do {
        digits[length++] = (char)('0' + (unsigned)(value % 10U));
        value /= 10U;
    } while (value != 0);
    while (length != 0U) {
        if (fputc((unsigned char)digits[--length], stream) == EOF) {
            return -1;
        }
    }
    return 0;
}

static void budget_reserve(MemoryBudget *budget, size_t bytes)
{
    if (bytes > budget->limit - budget->in_use) {
        fprintf(stderr,
                "error: DP memory budget exceeded: need another %.1f MiB "
                "with %.1f/%.1f MiB already in use; rerun with a larger "
                "--memory-mib value\n",
                (double)bytes / 1048576.0,
                (double)budget->in_use / 1048576.0,
                (double)budget->limit / 1048576.0);
        exit(EXIT_FAILURE);
    }
    budget->in_use += bytes;
    if (budget->peak < budget->in_use) {
        budget->peak = budget->in_use;
    }
}

static void budget_release(MemoryBudget *budget, size_t bytes)
{
    if (bytes > budget->in_use) {
        die("internal memory-budget underflow");
    }
    budget->in_use -= bytes;
}

static StateSlot *allocate_slots(MemoryBudget *budget, size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(StateSlot));
    budget_reserve(budget, bytes);
    StateSlot *slots = calloc(capacity, sizeof(StateSlot));
    if (slots == NULL) {
        fprintf(stderr,
                "error: could not allocate %.1f MiB for a DP table\n",
                (double)bytes / 1048576.0);
        exit(EXIT_FAILURE);
    }
    return slots;
}

static void free_slots(MemoryBudget *budget, StateSlot *slots,
                       size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(StateSlot));
    free(slots);
    budget_release(budget, bytes);
}

static HighSlot *allocate_high_slots(MemoryBudget *budget, size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(HighSlot));
    budget_reserve(budget, bytes);
    HighSlot *slots = calloc(capacity, sizeof(HighSlot));
    if (slots == NULL) {
        fprintf(stderr,
                "error: could not allocate %.1f MiB for high count words\n",
                (double)bytes / 1048576.0);
        exit(EXIT_FAILURE);
    }
    return slots;
}

static void free_high_slots(MemoryBudget *budget, HighSlot *slots,
                            size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(HighSlot));
    free(slots);
    budget_release(budget, bytes);
}

static uint64_t mix_key(uint64_t value)
{
    value ^= value >> 30U;
    value *= UINT64_C(0xbf58476d1ce4e5b9);
    value ^= value >> 27U;
    value *= UINT64_C(0x94d049bb133111eb);
    value ^= value >> 31U;
    return value;
}

static void map_init_with_capacity(StateMap *map, MemoryBudget *budget,
                                   size_t capacity)
{
    if (capacity < INITIAL_CAPACITY ||
        (capacity & (capacity - 1U)) != 0U) {
        die("internal non-power-of-two DP capacity");
    }
    map->capacity = capacity;
    map->size = 0;
    map->high_slots = NULL;
    map->high_capacity = 0;
    map->high_size = 0;
    map->budget = budget;
    map->slots = allocate_slots(budget, capacity);
}

static void map_init(StateMap *map, MemoryBudget *budget)
{
    map_init_with_capacity(map, budget, INITIAL_CAPACITY);
}

static void map_destroy(StateMap *map)
{
    if (map->slots != NULL) {
        free_slots(map->budget, map->slots, map->capacity);
    }
    if (map->high_slots != NULL) {
        free_high_slots(map->budget, map->high_slots, map->high_capacity);
    }
    map->slots = NULL;
    map->capacity = 0;
    map->size = 0;
    map->high_slots = NULL;
    map->high_capacity = 0;
    map->high_size = 0;
}

static StateSlot *map_find_slot(StateMap *map, uint64_t key_plus_one)
{
    size_t index = (size_t)mix_key(key_plus_one) & (map->capacity - 1U);
    for (;;) {
        StateSlot *slot = &map->slots[index];
        if (slot->key_plus_one == 0 ||
            slot->key_plus_one == key_plus_one) {
            return slot;
        }
        index = (index + 1U) & (map->capacity - 1U);
    }
}

static const StateSlot *map_find_const(const StateMap *map,
                                       uint64_t key_plus_one)
{
    size_t index = (size_t)mix_key(key_plus_one) & (map->capacity - 1U);
    for (;;) {
        const StateSlot *slot = &map->slots[index];
        if (slot->key_plus_one == 0 ||
            slot->key_plus_one == key_plus_one) {
            return slot;
        }
        index = (index + 1U) & (map->capacity - 1U);
    }
}

static void map_grow(StateMap *map)
{
    if (map->capacity > SIZE_MAX / 2U) {
        die("DP hash-table capacity overflow");
    }
    size_t old_capacity = map->capacity;
    StateSlot *old_slots = map->slots;
    size_t new_capacity = old_capacity * 2U;
    StateSlot *new_slots = allocate_slots(map->budget, new_capacity);

    map->capacity = new_capacity;
    map->slots = new_slots;
    for (size_t i = 0; i < old_capacity; ++i) {
        if (old_slots[i].key_plus_one != 0) {
            StateSlot *destination =
                map_find_slot(map, old_slots[i].key_plus_one);
            *destination = old_slots[i];
        }
    }
    free_slots(map->budget, old_slots, old_capacity);
}

static HighSlot *high_find_slot(StateMap *map, uint64_t key_plus_one)
{
    size_t index = (size_t)mix_key(key_plus_one) &
                   (map->high_capacity - 1U);
    for (;;) {
        HighSlot *slot = &map->high_slots[index];
        if (slot->key_plus_one == 0U ||
            slot->key_plus_one == key_plus_one) return slot;
        index = (index + 1U) & (map->high_capacity - 1U);
    }
}

static void high_grow(StateMap *map)
{
    size_t old_capacity = map->high_capacity;
    HighSlot *old_slots = map->high_slots;
    size_t new_capacity;
    if (old_capacity == 0U) {
        new_capacity = INITIAL_CAPACITY;
    } else {
        if (old_capacity > SIZE_MAX / 2U)
            die("high-count table capacity overflow");
        new_capacity = old_capacity * 2U;
    }
    map->high_capacity = new_capacity;
    map->high_slots = allocate_high_slots(map->budget, new_capacity);
    if (old_slots != NULL) {
        for (size_t i = 0; i < old_capacity; ++i) {
            if (old_slots[i].key_plus_one != 0U) {
                HighSlot *destination =
                    high_find_slot(map, old_slots[i].key_plus_one);
                *destination = old_slots[i];
            }
        }
        free_high_slots(map->budget, old_slots, old_capacity);
    }
}

static void map_add_high(StateMap *map, uint64_t key_plus_one,
                         uint64_t addend)
{
    if (addend == 0U) return;
    if (map->high_capacity == 0U) high_grow(map);
    HighSlot *slot = high_find_slot(map, key_plus_one);
    if (slot->key_plus_one != 0U) {
        if (UINT64_MAX - slot->count_high < addend)
            die("unsigned 128-bit count overflow");
        slot->count_high += addend;
        return;
    }
    if (map->high_size + 1U >
        (map->high_capacity / LOAD_DENOMINATOR) * LOAD_NUMERATOR) {
        high_grow(map);
        slot = high_find_slot(map, key_plus_one);
    }
    slot->key_plus_one = key_plus_one;
    slot->count_high = addend;
    ++map->high_size;
}

static Count128 map_get_count(const StateMap *map, const StateSlot *slot)
{
    Count128 result = {slot->count_low, 0U};
    if (map->high_capacity == 0U) return result;
    size_t index = (size_t)mix_key(slot->key_plus_one) &
                   (map->high_capacity - 1U);
    for (;;) {
        const HighSlot *high = &map->high_slots[index];
        if (high->key_plus_one == 0U) return result;
        if (high->key_plus_one == slot->key_plus_one) {
            result.high = high->count_high;
            return result;
        }
        index = (index + 1U) & (map->high_capacity - 1U);
    }
}

static void map_add(StateMap *map, uint64_t packed_key, Count128 addend)
{
    if (packed_key == UINT64_MAX) {
        die("packed state key overflow");
    }
    uint64_t key_plus_one = packed_key + UINT64_C(1);
    StateSlot *slot = map_find_slot(map, key_plus_one);
    if (slot->key_plus_one != 0) {
        uint64_t old_low = slot->count_low;
        slot->count_low += addend.low;
        uint64_t carry = slot->count_low < old_low ? UINT64_C(1) : UINT64_C(0);
        if (carry != 0U && addend.high == UINT64_MAX)
            die("unsigned 128-bit count overflow");
        map_add_high(map, key_plus_one, addend.high + carry);
        return;
    }

    if (map->size + 1U >
        (map->capacity / LOAD_DENOMINATOR) * LOAD_NUMERATOR) {
        map_grow(map);
        slot = map_find_slot(map, key_plus_one);
        if (slot->key_plus_one != 0) {
            die("internal duplicate state after table growth");
        }
    }
    slot->key_plus_one = key_plus_one;
    slot->count_low = addend.low;
    map_add_high(map, key_plus_one, addend.high);
    ++map->size;
}

static void map_clear(StateMap *map)
{
    size_t bytes = checked_product_size(map->capacity, sizeof(StateSlot));
    memset(map->slots, 0, bytes);
    map->size = 0;
    if (map->high_slots != NULL) {
        size_t high_bytes = checked_product_size(map->high_capacity,
                                                 sizeof(HighSlot));
        memset(map->high_slots, 0, high_bytes);
    }
    map->high_size = 0;
}

/*
 * next contains an obsolete layer.  Releasing it before reserving a likely
 * final capacity avoids the old+new transient allocation of map_grow near
 * the middle.  A later grow remains available if the estimate is low.
 */
static void map_prepare_next(StateMap *next, size_t desired_capacity)
{
    if (desired_capacity < INITIAL_CAPACITY) {
        desired_capacity = INITIAL_CAPACITY;
    }
    if ((desired_capacity & (desired_capacity - 1U)) != 0U) {
        die("internal non-power-of-two reserve capacity");
    }
    if (next->capacity == desired_capacity) {
        map_clear(next);
        return;
    }
    MemoryBudget *budget = next->budget;
    map_destroy(next);
    map_init_with_capacity(next, budget, desired_capacity);
}

static size_t capacity_for_entries(size_t entries)
{
    size_t capacity = INITIAL_CAPACITY;
    while ((capacity / LOAD_DENOMINATOR) * LOAD_NUMERATOR < entries) {
        if (capacity > SIZE_MAX / 2U)
            die("predicted DP capacity overflow");
        capacity *= 2U;
    }
    return capacity;
}

static uint64_t reverse_bits_64(uint64_t value)
{
    value = ((value & UINT64_C(0x5555555555555555)) << 1U) |
            ((value >> 1U) & UINT64_C(0x5555555555555555));
    value = ((value & UINT64_C(0x3333333333333333)) << 2U) |
            ((value >> 2U) & UINT64_C(0x3333333333333333));
    value = ((value & UINT64_C(0x0f0f0f0f0f0f0f0f)) << 4U) |
            ((value >> 4U) & UINT64_C(0x0f0f0f0f0f0f0f0f));
    value = ((value & UINT64_C(0x00ff00ff00ff00ff)) << 8U) |
            ((value >> 8U) & UINT64_C(0x00ff00ff00ff00ff));
    value = ((value & UINT64_C(0x0000ffff0000ffff)) << 16U) |
            ((value >> 16U) & UINT64_C(0x0000ffff0000ffff));
    return (value << 32U) | (value >> 32U);
}

static uint64_t reverse_low_bits(uint64_t mask, int n)
{
    return reverse_bits_64(mask) >> (64U - (unsigned)n);
}

static uint64_t pack_state(uint64_t used, unsigned a, unsigned b,
                           unsigned c, unsigned d)
{
    return (used << STATE_SHIFT) |
           ((uint64_t)a << (3U * ENDPOINT_BITS)) |
           ((uint64_t)b << (2U * ENDPOINT_BITS)) |
           ((uint64_t)c << ENDPOINT_BITS) | (uint64_t)d;
}

static void unpack_state(uint64_t packed, uint64_t *used, unsigned *a,
                         unsigned *b, unsigned *c, unsigned *d)
{
    *d = (unsigned)(packed & ENDPOINT_MASK);
    *c = (unsigned)((packed >> ENDPOINT_BITS) & ENDPOINT_MASK);
    *b = (unsigned)((packed >> (2U * ENDPOINT_BITS)) & ENDPOINT_MASK);
    *a = (unsigned)((packed >> (3U * ENDPOINT_BITS)) & ENDPOINT_MASK);
    *used = packed >> STATE_SHIFT;
}

static uint64_t canonical_state(uint64_t used, unsigned a, unsigned b,
                                unsigned c, unsigned d,
                                int n, bool use_symmetry)
{
    uint64_t original = pack_state(used, a, b, c, d);
    if (!use_symmetry) {
        return original;
    }
    uint64_t complemented = pack_state(
        reverse_low_bits(used, n),
        (unsigned)(n - 1 - (int)a),
        (unsigned)(n - 1 - (int)b),
        (unsigned)(n - 1 - (int)c),
        (unsigned)(n - 1 - (int)d));
    return original < complemented ? original : complemented;
}

static void make_masks(int n, uint64_t *bad)
{
    for (int value = 0; value < n; ++value) {
        bad[value] = 0;
        for (int other = 0; other < n; ++other) {
            int difference = value - other;
            if (difference > -5 && difference < 5) {
                bad[value] |= UINT64_C(1) << (unsigned)other;
            }
        }
    }
}

static void initialize_quadruples(StateMap *map, int n, const uint64_t *bad,
                                  bool use_symmetry)
{
    Count128 one = count_from_u64(UINT64_C(1));
    for (int a = 0; a < n; ++a) {
        for (int b = 0; b < n; ++b) {
            uint64_t b_bit = UINT64_C(1) << (unsigned)b;
            if ((bad[a] & b_bit) != 0U) continue;
            for (int c = 0; c < n; ++c) {
                uint64_t c_bit = UINT64_C(1) << (unsigned)c;
                if ((bad[a] & c_bit) != 0U || (bad[b] & c_bit) != 0U) continue;
                for (int d = 0; d < n; ++d) {
                    uint64_t d_bit = UINT64_C(1) << (unsigned)d;
                    if ((bad[a] & d_bit) != 0U ||
                        (bad[b] & d_bit) != 0U ||
                        (bad[c] & d_bit) != 0U) continue;
                    uint64_t used = (UINT64_C(1) << (unsigned)a) |
                                    b_bit | c_bit | d_bit;
                    uint64_t key = canonical_state(
                        used, (unsigned)a, (unsigned)b, (unsigned)c,
                        (unsigned)d, n, use_symmetry);
                    map_add(map, key, one);
                }
            }
        }
    }
}

static void extend_layer(const StateMap *current, StateMap *next,
                         int n, const uint64_t *bad,
                         bool use_symmetry, MitmStats *stats)
{
    for (size_t index = 0; index < current->capacity; ++index) {
        const StateSlot *slot = &current->slots[index];
        if (slot->key_plus_one == 0) {
            continue;
        }
        uint64_t used;
        unsigned a;
        unsigned b;
        unsigned c;
        unsigned d;
        unpack_state(slot->key_plus_one - UINT64_C(1),
                     &used, &a, &b, &c, &d);
        Count128 state_count = map_get_count(current, slot);
        uint64_t full = (UINT64_C(1) << (unsigned)n) - UINT64_C(1);
        uint64_t candidates = full & ~(bad[a] | bad[b] | bad[c] | bad[d]) &
                              ~used;
        while (candidates != 0) {
            uint64_t bit = candidates & (UINT64_C(0) - candidates);
            candidates ^= bit;
#if defined(__GNUC__) || defined(__clang__)
            unsigned e = (unsigned)__builtin_ctzll(bit);
#else
            unsigned e = 0;
            while ((bit >> e) != UINT64_C(1)) {
                ++e;
            }
#endif
            uint64_t key = canonical_state(used | bit, b, c, d, e, n,
                                           use_symmetry);
            map_add(next, key, state_count);
            if (stats->prefix_transitions == UINT64_MAX) {
                die("prefix transition counter overflow");
            }
            ++stats->prefix_transitions;
        }
    }
}

typedef struct {
    uint64_t packed_key;
    Count128 count;
} EndpointRecord;

static int compare_records(const void *left, const void *right)
{
    const EndpointRecord *a = left;
    const EndpointRecord *b = right;
    return a->packed_key < b->packed_key ? -1 :
           a->packed_key > b->packed_key ? 1 : 0;
}

static EndpointRecord *collect_records(const StateMap *map, int n,
                                       bool use_symmetry,
                                       size_t *record_count)
{
    size_t multiplier = use_symmetry ? 2U : 1U;
    size_t capacity = checked_product_size(map->size, multiplier);
    size_t allocation_capacity = capacity == 0U ? 1U : capacity;
    size_t bytes = checked_product_size(allocation_capacity,
                                        sizeof(EndpointRecord));
    budget_reserve(map->budget, bytes);
    EndpointRecord *records = malloc(bytes);
    if (records == NULL) die("out of memory collecting endpoint records");
    size_t count = 0;
    for (size_t i = 0; i < map->capacity; ++i) {
        const StateSlot *slot = &map->slots[i];
        if (slot->key_plus_one == 0U) continue;
        uint64_t packed = slot->key_plus_one - UINT64_C(1);
        Count128 value = map_get_count(map, slot);
        if (use_symmetry) value = count_halve(value);
        records[count++] = (EndpointRecord){packed, value};
        if (use_symmetry) {
            uint64_t used;
            unsigned a, b, c, d;
            unpack_state(packed, &used, &a, &b, &c, &d);
            uint64_t reflected = pack_state(
                reverse_low_bits(used, n),
                (unsigned)(n - 1 - (int)a),
                (unsigned)(n - 1 - (int)b),
                (unsigned)(n - 1 - (int)c),
                (unsigned)(n - 1 - (int)d));
            records[count++] = (EndpointRecord){reflected, value};
        }
    }
    if (count > 1U) qsort(records, count, sizeof(*records), compare_records);
    *record_count = count;
    return records;
}

static void free_records(const StateMap *map, EndpointRecord *records,
                         size_t record_count, bool use_symmetry)
{
    (void)record_count;
    size_t multiplier = use_symmetry ? 2U : 1U;
    size_t capacity = checked_product_size(map->size, multiplier);
    size_t allocation_capacity = capacity == 0U ? 1U : capacity;
    size_t bytes = checked_product_size(allocation_capacity,
                                        sizeof(EndpointRecord));
    free(records);
    budget_release(map->budget, bytes);
}

static size_t lower_bound_used(const EndpointRecord *records, size_t count,
                               uint64_t used)
{
    size_t first = 0, length = count;
    while (length != 0U) {
        size_t half = length / 2U;
        size_t middle = first + half;
        uint64_t middle_used = records[middle].packed_key >> STATE_SHIFT;
        if (middle_used < used) {
            first = middle + 1U;
            length -= half + 1U;
        } else {
            length = half;
        }
    }
    return first;
}

static Count128 join_halves(const StateMap *left_map,
                            const StateMap *right_map,
                            int n, int left_length,
                            const uint64_t *bad,
                            bool use_symmetry, MitmStats *stats)
{
    uint64_t full = (UINT64_C(1) << (unsigned)n) - UINT64_C(1);
    bool equal_halves = left_length * 2 == n;
    size_t left_count, right_count;
    EndpointRecord *left = collect_records(left_map, n, use_symmetry,
                                           &left_count);
    EndpointRecord *right;
    if (left_map == right_map) {
        right = left;
        right_count = left_count;
    } else {
        right = collect_records(right_map, n, use_symmetry, &right_count);
    }

    Count128 total = count_zero();
    size_t left_begin = 0;
    while (left_begin < left_count) {
        uint64_t subset = left[left_begin].packed_key >> STATE_SHIFT;
        size_t left_end = left_begin + 1U;
        while (left_end < left_count &&
               (left[left_end].packed_key >> STATE_SHIFT) == subset)
            ++left_end;
        uint64_t complement = full ^ subset;
        if (!equal_halves || subset < complement) {
            size_t right_begin = lower_bound_used(right, right_count,
                                                  complement);
            if (right_begin < right_count &&
                (right[right_begin].packed_key >> STATE_SHIFT) == complement) {
                size_t right_end = right_begin + 1U;
                while (right_end < right_count &&
                       (right[right_end].packed_key >> STATE_SHIFT) ==
                           complement)
                    ++right_end;
                if (stats->split_subsets == UINT64_MAX)
                    die("split-subset counter overflow");
                ++stats->split_subsets;

                for (size_t li = left_begin; li < left_end; ++li) {
                    uint64_t left_used;
                    unsigned a, b, c, d;
                    unpack_state(left[li].packed_key, &left_used,
                                 &a, &b, &c, &d);
                    (void)left_used;
                    for (size_t ri = right_begin; ri < right_end; ++ri) {
                        uint64_t right_used;
                        unsigned h, g, f, e;
                        unpack_state(right[ri].packed_key, &right_used,
                                     &h, &g, &f, &e);
                        (void)right_used;
                        uint64_t e_bit = UINT64_C(1) << e;
                        uint64_t f_bit = UINT64_C(1) << f;
                        uint64_t g_bit = UINT64_C(1) << g;
                        uint64_t h_bit = UINT64_C(1) << h;
                        if ((bad[d] & (e_bit | f_bit | g_bit | h_bit)) != 0U ||
                            (bad[c] & (e_bit | f_bit | g_bit)) != 0U ||
                            (bad[b] & (e_bit | f_bit)) != 0U ||
                            (bad[a] & e_bit) != 0U)
                            continue;
                        count_add_to(&total,
                            count_multiply(left[li].count, right[ri].count));
                        if (stats->joined_endpoint_pairs == UINT64_MAX)
                            die("joined endpoint-quadruple counter overflow");
                        ++stats->joined_endpoint_pairs;
                    }
                }
            }
        }
        left_begin = left_end;
    }

    if (equal_halves) count_add_to(&total, total);
    if (right != left)
        free_records(right_map, right, right_count, use_symmetry);
    free_records(left_map, left, left_count, use_symmetry);
    return total;
}

static bool permutation_is_valid(const int *permutation, int n)
{
    for (int i = 0; i < n; ++i) {
        for (int distance = 1; distance <= 4 && i + distance < n;
             ++distance) {
            int difference = permutation[i + distance] - permutation[i];
            if (difference > -5 && difference < 5) return false;
        }
    }
    return true;
}

static bool next_permutation(int *permutation, int n)
{
    int i = n - 2;
    while (i >= 0 && permutation[i] >= permutation[i + 1]) {
        --i;
    }
    if (i < 0) {
        return false;
    }
    int j = n - 1;
    while (permutation[j] <= permutation[i]) {
        --j;
    }
    int temporary = permutation[i];
    permutation[i] = permutation[j];
    permutation[j] = temporary;
    for (int left = i + 1, right = n - 1; left < right;
         ++left, --right) {
        temporary = permutation[left];
        permutation[left] = permutation[right];
        permutation[right] = temporary;
    }
    return true;
}

static Count128 direct_count(int n)
{
    if (n == 0) {
        return count_from_u64(UINT64_C(1));
    }
    int permutation[DIRECT_CHECK_MAX_N];
    for (int i = 0; i < n; ++i) {
        permutation[i] = i;
    }
    Count128 result = count_zero();
    do {
        if (permutation_is_valid(permutation, n)) {
            count_add_to(&result, count_from_u64(UINT64_C(1)));
        }
    } while (next_permutation(permutation, n));
    return result;
}

static void verify_reference(Count128 value, int n)
{
    if (n <= REFERENCE_MAX_N) {
        Count128 expected = parse_count(reference_terms[n]);
        if (!count_equal(value, expected)) {
            fprintf(stderr, "error: A322308 mismatch at n=%d: got ", n);
            (void)fprint_count(stderr, value);
            fprintf(stderr, ", expected %s\n", reference_terms[n]);
            exit(EXIT_FAILURE);
        }
    }
    if (n > 1 && (value.low & UINT64_C(1)) != 0) {
        fprintf(stderr, "error: parity check failed at n=%d\n", n);
        exit(EXIT_FAILURE);
    }
}

static Count128 compute_mitm(int n, bool use_symmetry,
                             uint64_t memory_mib, MitmStats *stats)
{
    double started = monotonic_seconds();
    memset(stats, 0, sizeof(*stats));
    if (n <= 7) {
        Count128 result = direct_count(n);
        stats->total_seconds = monotonic_seconds() - started;
        return result;
    }

    int left_length = n / 2;
    int right_length = n - left_length;
    uint64_t bad[MAX_SUPPORTED_N] = {0};
    make_masks(n, bad);

    MemoryBudget budget;
    budget.limit = checked_product_size((size_t)memory_mib,
                                        (size_t)UINT64_C(1048576));
    budget.in_use = 0;
    budget.peak = 0;

    StateMap current;
    StateMap next;
    map_init(&current, &budget);
    map_init(&next, &budget);
    initialize_quadruples(&current, n, bad, use_symmetry);

    double build_started = monotonic_seconds();
    size_t previous_layer_size = 0U;
    for (int length = 4;
         length < right_length && current.size != 0U; ++length) {
        size_t predicted_entries;
        if (previous_layer_size == 0U) {
            predicted_entries = current.size;
        } else {
            if (current.size != 0U && current.size > SIZE_MAX / current.size)
                die("predicted DP state count overflow");
            size_t square = current.size * current.size;
            size_t raw = square / previous_layer_size;
            if (square % previous_layer_size != 0U) ++raw;
            if (raw > current.size) {
                size_t excess = raw - current.size;
                size_t carried = excess / 3U +
                                 (excess % 3U != 0U ? 1U : 0U);
                if (carried > SIZE_MAX - current.size)
                    die("predicted DP growth overflow");
                predicted_entries = current.size + carried;
            } else {
                predicted_entries = raw;
            }
        }
        size_t desired = capacity_for_entries(predicted_entries);
        map_prepare_next(&next, desired);
        previous_layer_size = current.size;
        extend_layer(&current, &next, n, bad,
                     use_symmetry, stats);
        StateMap temporary = current;
        current = next;
        next = temporary;
    }
    stats->build_seconds = monotonic_seconds() - build_started;
    stats->peak_bytes = budget.peak;

    const StateMap *left_map;
    const StateMap *right_map;
    if (left_length == right_length) {
        left_map = &current;
        right_map = &current;
        stats->left_states = current.size;
        stats->right_states = current.size;
        map_destroy(&next);
    } else {
        /* Last swap left the length-m layer in next and length-r in current. */
        left_map = &next;
        right_map = &current;
        stats->left_states = next.size;
        stats->right_states = current.size;
    }

    double join_started = monotonic_seconds();
    Count128 result = join_halves(left_map, right_map, n, left_length,
                                  bad, use_symmetry, stats);
    stats->join_seconds = monotonic_seconds() - join_started;

    map_destroy(&current);
    map_destroy(&next);
    if (budget.in_use != 0U) {
        die("internal DP memory leak");
    }
    stats->total_seconds = monotonic_seconds() - started;
    return result;
}

static Count128 compute_value(int n, bool use_symmetry,
                              uint64_t memory_mib, bool verbose)
{
    MitmStats stats;
    Count128 value = compute_mitm(n, use_symmetry, memory_mib, &stats);
    verify_reference(value, n);
    if (verbose) {
        fprintf(stderr,
                "322308_02: n=%d, MITM %s, left/right states=%zu/%zu, "
                "prefix transitions=%" PRIu64 ", split subsets=%" PRIu64
                ", joined endpoint quadruples=%" PRIu64
                ", peak table memory=%.1f MiB, build/join/total="
                "%.3f/%.3f/%.3f s\n",
                n, use_symmetry ? "complement-quotient" : "plain",
                stats.left_states, stats.right_states,
                stats.prefix_transitions, stats.split_subsets,
                stats.joined_endpoint_pairs,
                (double)stats.peak_bytes / 1048576.0,
                stats.build_seconds, stats.join_seconds,
                stats.total_seconds);
    }
    return value;
}

static int check_implementation(int maximum_n, uint64_t memory_mib)
{
    if (maximum_n > REFERENCE_MAX_N) {
        fprintf(stderr, "error: CHECK_N must be in 0..%d: %d\n",
                REFERENCE_MAX_N, maximum_n);
        return EXIT_FAILURE;
    }
    /* Explicitly test carry propagation and sparse high-word lookup; the
     * currently known terms themselves do not require a high state word. */
    {
        MemoryBudget budget = {1024U * 1024U, 0U, 0U};
        StateMap test;
        map_init(&test, &budget);
        Count128 first = {UINT64_MAX, UINT64_C(5)};
        Count128 second = {UINT64_C(2), UINT64_C(7)};
        map_add(&test, UINT64_C(123), first);
        map_add(&test, UINT64_C(123), second);
        const StateSlot *slot = map_find_const(&test, UINT64_C(124));
        Count128 expected = {UINT64_C(1), UINT64_C(13)};
        if (!count_equal(map_get_count(&test, slot), expected))
            die("sparse high-word count self-test failed");
        map_destroy(&test);
        if (budget.in_use != 0U)
            die("sparse high-word count self-test leaked memory");
    }
    for (int n = 0; n <= maximum_n; ++n) {
        Count128 quotient = compute_value(n, true, memory_mib, false);
        if (n <= SYMMETRY_CHECK_MAX_N) {
            Count128 plain = compute_value(n, false, memory_mib, false);
            if (!count_equal(quotient, plain)) {
                fprintf(stderr,
                        "error: MITM symmetry/plain mismatch at n=%d: ", n);
                (void)fprint_count(stderr, quotient);
                fputs(" versus ", stderr);
                (void)fprint_count(stderr, plain);
                fputc('\n', stderr);
                return EXIT_FAILURE;
            }
        }
        if (n <= DIRECT_CHECK_MAX_N) {
            Count128 direct = direct_count(n);
            if (!count_equal(quotient, direct)) {
                fprintf(stderr,
                        "error: MITM/direct-permutation mismatch at n=%d: ",
                        n);
                (void)fprint_count(stderr, quotient);
                fputs(" versus ", stderr);
                (void)fprint_count(stderr, direct);
                fputc('\n', stderr);
                return EXIT_FAILURE;
            }
        }
    }
    printf("ok: MITM agrees with OEIS through n=%d and 322308_01 "
           "regression terms through n=%d; independent full-permutation "
           "scan through n=%d; symmetry/plain MITM through n=%d\n",
           maximum_n < OEIS_MAX_N ? maximum_n : OEIS_MAX_N,
           maximum_n,
           maximum_n < DIRECT_CHECK_MAX_N
               ? maximum_n : DIRECT_CHECK_MAX_N,
           maximum_n < SYMMETRY_CHECK_MAX_N
               ? maximum_n : SYMMETRY_CHECK_MAX_N);
    return EXIT_SUCCESS;
}

static char *path_beside_executable(const char *argv0,
                                    const char *filename)
{
    char executable[PATH_MAX];
    char resolved[PATH_MAX];
    bool found = false;
#ifdef __APPLE__
    uint32_t size = (uint32_t)sizeof(executable);
    if (_NSGetExecutablePath(executable, &size) == 0) {
        found = true;
    }
#elif defined(__linux__)
    ssize_t length = readlink("/proc/self/exe", executable,
                              sizeof(executable) - 1U);
    if (length >= 0) {
        executable[length] = '\0';
        found = true;
    }
#endif
    if (!found) {
        size_t length = strlen(argv0);
        if (length >= sizeof(executable)) {
            die("executable path is too long");
        }
        memcpy(executable, argv0, length + 1U);
    }
    const char *base = realpath(executable, resolved);
    if (base == NULL) {
        base = executable;
    }
    const char *slash = strrchr(base, '/');
    size_t directory_length =
        slash == NULL ? 1U : (size_t)(slash - base);
    if (slash != NULL && directory_length == 0U) {
        directory_length = 1U;
    }
    size_t filename_length = strlen(filename);
    if (directory_length > SIZE_MAX - filename_length - 2U) {
        die("output path length overflow");
    }
    char *path = malloc(directory_length + filename_length + 2U);
    if (path == NULL) {
        die("out of memory while making output path");
    }
    if (slash == NULL) {
        path[0] = '.';
    } else if (slash == base) {
        path[0] = '/';
    } else {
        memcpy(path, base, directory_length);
    }
    path[directory_length] = '/';
    memcpy(path + directory_length + 1U, filename,
           filename_length + 1U);
    return path;
}

static void produce_file(const char *argv0, int maximum_n,
                         bool use_symmetry, uint64_t memory_mib)
{
    char *final_path =
        path_beside_executable(argv0, "b322308_02.txt");
    char *part_path =
        path_beside_executable(argv0, "b322308_02_part.txt");
    FILE *stream = fopen(part_path, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: cannot open %s: %s\n",
                part_path, strerror(errno));
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }
    for (int n = SEQUENCE_OFFSET; n <= maximum_n; ++n) {
        Count128 value = compute_value(n, use_symmetry,
                                       memory_mib, true);
        if (fprintf(stream, "%d ", n) < 0 ||
            fprint_count(stream, value) != 0 ||
            fputc('\n', stream) == EOF || fflush(stream) != 0) {
            (void)fclose(stream);
            free(final_path);
            free(part_path);
            die("could not write the A322308 MITM output file");
        }
    }
    if (fclose(stream) != 0) {
        free(final_path);
        free(part_path);
        die("could not close the A322308 MITM output file");
    }
    if (rename(part_path, final_path) != 0) {
        fprintf(stderr, "error: cannot rename %s to %s: %s\n",
                part_path, final_path, strerror(errno));
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }
    printf("wrote %s (n=%d..%d)\n",
           final_path, SEQUENCE_OFFSET, maximum_n);
    free(final_path);
    free(part_path);
}

static void usage(const char *program)
{
    fprintf(stderr,
            "usage: %s [MAX_N] [--memory-mib M] [--no-symmetry]\n"
            "       %s --upto MAX_N [--memory-mib M] [--no-symmetry]\n"
            "       %s --term N [--memory-mib M] [--no-symmetry]\n"
            "       %s --check [MAX_N] [--memory-mib M]\n"
            "\n"
            "N and MAX_N may be %d..%d; 128-bit result arithmetic is "
            "proved safe throughout.\n"
            "The default is --upto %d with a %" PRIu64
            " MiB DP-table budget.\n"
            "A range run writes b322308_02.txt beside the executable.\n"
            "--no-symmetry is slower and is mainly a diagnostic.\n",
            program, program, program, program,
            SEQUENCE_OFFSET, MAX_SUPPORTED_N, DEFAULT_MAX_N,
            DEFAULT_MEMORY_MIB);
}

int main(int argc, char **argv)
{
    if (argc == 2 &&
        (strcmp(argv[1], "--help") == 0 ||
         strcmp(argv[1], "-h") == 0)) {
        usage(argv[0]);
        return EXIT_SUCCESS;
    }

    RunMode mode = RUN_UPTO;
    int n = -1;
    bool have_n = false;
    bool have_mode = false;
    bool use_symmetry = true;
    bool have_symmetry_option = false;
    uint64_t memory_mib = DEFAULT_MEMORY_MIB;
    bool have_memory = false;

    for (int argument = 1; argument < argc; ++argument) {
        const char *text = argv[argument];
        if (strcmp(text, "--memory-mib") == 0) {
            if (have_memory || argument + 1 >= argc) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            memory_mib = parse_memory_mib(argv[++argument]);
            have_memory = true;
        } else if (strcmp(text, "--no-symmetry") == 0) {
            if (have_symmetry_option) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            use_symmetry = false;
            have_symmetry_option = true;
        } else if (strcmp(text, "--term") == 0 ||
                   strcmp(text, "--upto") == 0) {
            if (have_mode || have_n || argument + 1 >= argc) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            mode = strcmp(text, "--term") == 0 ? RUN_TERM : RUN_UPTO;
            have_mode = true;
            n = parse_n(argv[++argument],
                        mode == RUN_TERM ? "N" : "MAX_N");
            have_n = true;
        } else if (strcmp(text, "--check") == 0) {
            if (have_mode || have_n) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            mode = RUN_CHECK;
            have_mode = true;
            if (argument + 1 < argc && argv[argument + 1][0] != '-') {
                n = parse_n(argv[++argument], "CHECK_N");
                have_n = true;
            }
        } else if (text[0] == '-' || have_n) {
            usage(argv[0]);
            return EXIT_FAILURE;
        } else {
            n = parse_n(text,
                        mode == RUN_CHECK ? "CHECK_N" : "MAX_N");
            have_n = true;
        }
    }

    if (!have_n) {
        n = mode == RUN_CHECK ? DEFAULT_CHECK_N : DEFAULT_MAX_N;
    }
    if (mode == RUN_CHECK) {
        return check_implementation(n, memory_mib);
    }
    if (mode == RUN_TERM) {
        Count128 value = compute_value(n, use_symmetry,
                                       memory_mib, true);
        printf("%d ", n);
        if (fprint_count(stdout, value) != 0 || fputc('\n', stdout) == EOF) {
            die("could not write result");
        }
        return EXIT_SUCCESS;
    }
    produce_file(argv[0], n, use_symmetry, memory_mib);
    return EXIT_SUCCESS;
}
